version: '3'

services:
  internal-app:
    image: email_service:0.0.1
    build:
      context: .
      # dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    expose:
      - 8000
    restart: unless-stopped